from django.urls import path, include
from .views import ProjectViewSet
from rest_framework import routers

# Create a DefaultRouter instance
router = routers.DefaultRouter()

# Register the ProjectViewSet with the router, specifying the basename 'project'
router.register('project', ProjectViewSet, basename='project')

# Define the urlpatterns
urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls))
]
