# Generated by Django 5.0.2 on 2024-04-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='creator',
        ),
    ]
