# Generated by Django 5.0.2 on 2024-04-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_data_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_by',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
