# Generated by Django 5.0.2 on 2024-04-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_uploadedfile_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
