# Generated by Django 5.0.2 on 2024-04-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_remove_filter_filters_filter_filter_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='filter_data',
            field=models.CharField(max_length=200),
        ),
    ]
