# Generated by Django 5.0.2 on 2024-04-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_alter_filter_filter_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='user',
            new_name='email',
        ),
    ]
