# Generated by Django 5.0.2 on 2024-04-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0004_rename_user_filter_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='email',
            new_name='user',
        ),
    ]
