# Generated by Django 5.0.2 on 2024-03-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_projects_project_no_alter_projects_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
