# Generated by Django 5.0.2 on 2024-03-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_norms_acidityofoil_remove_norms_aftertaste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='norms',
            name='acidityofoil',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='aftertaste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='appearance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='aromaorsmell',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='aromaorsmellaftermixingwithsalad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='aromasmell',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='attractivedesign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='attractiveorlikepackcolour',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='attractiveshapeorlikeshape',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='believability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='bitterness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='blindbranded',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='bodyorvolumeofhairpostwashing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='bounceofhairpostwashing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='burningorscarringofscalpduetotheproductapplied',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='carbonation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='cheesetaste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='clientname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='colour',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='colourofhairpostwashing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='comfortonfingers',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='comprehension',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='concept_uniqueness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='concept_valueformoney',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='convenienttouse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='countrycode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='creaminess',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='creamytaste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='creamytexture',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='crispiness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='doesnotirritateorstingoritch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='easeoffixing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='easeofgripping',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='easeofholding',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='easeofmixingduringfoodpreparation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='easeofoplaiting',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='easeofsplitting',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='easeofspreading',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='easeoftrimming',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='efficacyoftheproduct',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='elegantlook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='exactage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='extentoftangingduringcombing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='extentoftangingduringfixing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='eyecatching',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='fattiness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='firmness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='flavor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='freshingredients',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='freshness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='freshtaste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='genderofrespondent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='goodqualitymaterial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='hairfallwhileapplying',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='hairfallwhilewashingofftheproduct',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='hairstrengthafterwashingofftheproduct',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='heavinessofbraids',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='indulgingtaste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='innovativedesign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='lightness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='likelihoodtorecommend',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='liking',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='mildorgentle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='milkiness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='milkyaroma',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='modernorcontemporarylook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='mouthfeel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='mouthfeeloffruitpieces',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='naturalsaltiness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='naturalsweetness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='naturaltaste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='naturaltasteoffruitpieces',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='neatnessofplaits',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='oiliness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='overallattractiveness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='overallopinion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='overallopiniononfinallook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='overalltimetakenintheentireprocess',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='pack_relevance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='pack_uniqueness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='pack_valueformoney',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='placeofinterview',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='pourability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='premiumlook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='productcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='productformat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='purchaseintentionpriced',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='purchaseintentionunpriced',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='qtyoffruitpieces',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='qualityofpotato',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='quantityinsinglepack',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='relevance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='relevanceoverall',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='respondentid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='safetouse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='saltiness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='scaleoverallopinion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='scaleproductattributes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='scalepurchaseintention',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='secnew',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='shine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='shineofbraids',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='shineofhairextension',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='shineofhairpostwashing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='sizeoffruitpieces',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='smellorfragrance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='smoothness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='smoothnessofbraids',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='smoothnessofhairextension',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='softnessofbraids',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='softnessofhairextension',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='sourness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='spreadability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='stickiness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='stomachfeel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='straighteningofhairpostwashing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='strengthofhairextension',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='studydesign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='studytype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='suitableforinhomeuse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='suitableforoutofhomeuse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='supercategory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='sweetness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='taste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='tastegoodforbreakfast',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='tasteofenddish',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='tasteoffruitpieces',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='tasteofmilk',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='tasterichincream',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='texture',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='textureorconsistency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='thickness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='thicknessofbraids',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='thicknessorconsistency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='traditionallook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='uniqueness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='valueformoney',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='variant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='wellsealed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='norms',
            name='wouldstandoutonshelf',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
